### ISSUE TITLE
Enhance feedback for creating artifacts.yaml

### ISSUE THREAD

**Issue by jellebouwman** [iterative/gto#177]
I created a new scratch `gto` repository to test out some things. When I used `gto annotate` with a couple of flags, I received some nice error messages when I made a typo or a mistake. 👍 

After fiddling, I ended up with:
<img width="681" alt="Screenshot 2022-06-20 at 08 44 20" src="https://user-images.githubusercontent.com/32744870/174511233-096bf569-bcaa-4a15-bd95-b2c1cb5a29f9.png">

After I hit 'return', only a new line was printed.

It might be nice for GTO to output some message to the user stating that:

- `artifacts.yaml` was not yet found, so `gto` created it in the root of the repository
- GTO succesfully wrote your `gto annotate` action to `artifacts.yaml`

(optional, don't know if we want this): `gto` shows the new state of the object that was annotated. In this case:
```
churn:
  description: This is a model called churn, it is saved as a .pkl file
  labels:
  - some,labels,that,are,comma,seperated
  path: models/churn.pkl
  type: model
  virtual: false
```
