### ISSUE TITLE
Add a field for arbitrary metadata in annotation

### ISSUE THREAD

**Issue by aguschin** [iterative/gto#313]
For some, it can be useful to keep arbitrary metadata. Since `artifacts.yaml` is a yaml file, it could be `yaml` or anything that works. Something like:

```yaml
mymodel:
  path: path/to/model
  extra: <.......arbitrary metadata.....>
```
