### ISSUE TITLE
Deploy the same artifact to different endpoints

### ISSUE THREAD

**Issue by aguschin** [iterative/gto#314]
This use case is reported by the client: deploying the same model (e.g. `path: models/rf`) as two different endpoints in the same stage.
One way is to create two artifacts:
```yaml
churn-classification-germany:
  path: models/rf
churn-classification-ireland:
  path: models/rf
```
Rn GTO prevents you from annotating two models with the same path. We can allow bypassing this limitation, e.g.:
```shell
$ gto annotate churn-classification-scotland --path models/rf --allow-path-reuse
```

Q: are there other solutions to the problem?
