### ISSUE TITLE
Can refer to the same filepath by multiple artifacts

### ISSUE THREAD

**Issue by omesser** [iterative/gto#59]
There's nothing preventing this but I don't think it makes sense, perhaps we'd want to prevent that? It doesn't make sense for models but also not sure it makes sense for any other trackable artifact and will cause troubles if happening by mistake
e.g.
```shell
❯ gto add mymodel model models/m1.txt
❯ gto add mymodel2 models models/m1.txt
```
and `artifacts.yaml` will show:
```yaml
mymodel:
  name: mymodel
  path: models/m1.txt
  type: model
mymodel2:
  name: mymodel2
  path: models/m1.txt
  type: model
```
